### ISSUE TITLE
commerce-gateways.php deprecated

### ISSUE THREAD

**Issue by zackspear** [webdna/commerce-braintree#35]
[Craft Commerce release 3.3.0 - 2021-04-20](https://github.com/craftcms/commerce/blob/develop/CHANGELOG.md#330---2021-04-20)

Deprecated craft\commerce\services\Gateways::getGatewayOverrides() and the commerce-gateways.php config file. Gateway-specific config files should be used instead. (#1963)

**Comment by samuelbirch** [comment]
closing for Commerce v4+ support
